In [2]:
import pandas as pd
import re

In [3]:
sexism_data = pd.read_csv('twitter_sexism_parsed_dataset.csv')

In [4]:
sexism_data.head()

,index,id,Text,Annotation,oh_label
0,5.35198627292254E+017,5.35198627292254E+017,RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...,sexism,1.0
1,5.75984924030714E+017,5.75984924030714E+017,There's some very hate able teams this year #MKR,none,0.0
2,5.7233536016588E+017,5.7233536016588E+017,"RT @The_Eccles: ""Everyone underestimated us"" \...",none,0.0
3,5.72337925708374E+017,5.72337925708374E+017,RT @NOTLukeDarcy: did @Channel7 or #MKR actual...,none,0.0
4,4.43033024528011E+017,4.43033024528011E+017,"No, you don't. @Shut_Up_Jeff: I thought of a r...",sexism,1.0

In [5]:
sexism_data_1 = sexism_data[sexism_data['oh_label'] == 1]  # Records where oh_label is 1
sexism_data_0 = sexism_data[sexism_data['oh_label'] == 0]  # Records where oh_label is 0

In [9]:
def format_id(value):
    try:
        value_int = int(float(value))  # Ensure it's converted properly
        value_str = str(value_int)  # Convert to string for formatting
        return f"{value_str[:4]}-{value_str[4:8]}-{value_str[8:12]}-{value_str[12:16]}-{value_str[16:]}"
    except ValueError:
        return None  # Handle any conversion errors gracefully

In [8]:
sexism_data_1 = pd.DataFrame(sexism_data_1)

In [10]:
# Apply formatting to 'index' and 'id' columns
sexism_data_1['formatted_index'] = sexism_data_1['index'].apply(format_id)
sexism_data_1['formatted_id'] = sexism_data_1['id'].apply(format_id)

In [11]:
# Display the updated dataframe
sexism_data_1[['formatted_index', 'formatted_id']].head()

           formatted_index            formatted_id
0   5351-9862-7292-2540-16  5351-9862-7292-2540-16
4   4430-3302-4528-0110-08  4430-3302-4528-0110-08
5   5695-7728-6308-9870-08  5695-7728-6308-9870-08
10  5684-3616-8649-3429-76  5684-3616-8649-3429-76
13  4269-6640-5339-0300-16  4269-6640-5339-0300-16

In [12]:
def extract_and_remove_mentions_hashtags_links(text):
    usernames = re.findall(r'@\w+', text)  # Extract usernames
    hashtags = re.findall(r'#\w+', text)  # Extract hashtags
    links = re.findall(r'http[s]?://\S+', text)  # Extract links starting with http
    clean_text = re.sub(r'@\w+|#\w+|http[s]?://\S+', '', text).strip()  # Remove usernames, hashtags, and links
    return clean_text, ' '.join(usernames), ' '.join(hashtags), ' '.join(links)  # Return cleaned text and extracted words

In [13]:
sexism_data_1[['cleaned_text', 'users', 'hashtags','links']] = sexism_data_1['Text'].apply(lambda x: pd.Series(extract_and_remove_mentions_hashtags_links(x)))

In [14]:
sexism_data_1[['cleaned_text', 'users', 'hashtags','links']].head()

,cleaned_text,users,hashtags,links
0,RT : : I'm not sexist but fuck if you're a wo...,@BeepsS @senna1 @BeepsS,,
4,"No, you don't. : I thought of a really funny j...",@Shut_Up_Jeff,,
5,RT : You might like this,@Wateronatrain @MT8_9,#patriarchy,http://t.co/c9m2pFmFJ3
10,"RT : But yea, apparently women are sock puppe...",@MetalBarbieDoll,#GamerGate,http://t.co/4WouDly45a
13,:D Dudes who go to culinary school: :),@nkrause11,#why #findawife #notsexist,

In [15]:
sexism_data_1.head()

,index,id,Text,Annotation,oh_label,formatted_index,formatted_id,cleaned_text,users,hashtags,links
0,5.35198627292254E+017,5.35198627292254E+017,RT @BeepsS: @senna1 @BeepsS: I'm not sexist bu...,sexism,1.0,5351-9862-7292-2540-16,5351-9862-7292-2540-16,RT : : I'm not sexist but fuck if you're a wo...,@BeepsS @senna1 @BeepsS,,
4,4.43033024528011E+017,4.43033024528011E+017,"No, you don't. @Shut_Up_Jeff: I thought of a r...",sexism,1.0,4430-3302-4528-0110-08,4430-3302-4528-0110-08,"No, you don't. : I thought of a really funny j...",@Shut_Up_Jeff,,
5,5.69577286308987E+017,5.69577286308987E+017,RT @Wateronatrain: @MT8_9 You might like this ...,sexism,1.0,5695-7728-6308-9870-08,5695-7728-6308-9870-08,RT : You might like this,@Wateronatrain @MT8_9,#patriarchy,http://t.co/c9m2pFmFJ3
10,5.68436168649343E+017,5.68436168649343E+017,"RT @MetalBarbieDoll: But yea, apparently #Game...",sexism,1.0,5684-3616-8649-3429-76,5684-3616-8649-3429-76,"RT : But yea, apparently women are sock puppe...",@MetalBarbieDoll,#GamerGate,http://t.co/4WouDly45a
13,4.2696640533903E+017,4.2696640533903E+017,:D @nkrause11 Dudes who go to culinary school:...,sexism,1.0,4269-6640-5339-0300-16,4269-6640-5339-0300-16,:D Dudes who go to culinary school: :),@nkrause11,#why #findawife #notsexist,

In [16]:
# Reorder and drop unnecessary columns
sexism_data_1 = sexism_data_1[['formatted_index', 'formatted_id', 'cleaned_text', 'Annotation', 'oh_label', 'users', 'hashtags', 'links']]

In [17]:
# Save the cleaned dataframe to a CSV file
sexism_data_1.to_csv('sexism_cleaned_dataset.csv', index=False)